/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iphone.glb -T 
Files: iphone.glb [11.15MB] > D:\Projects\mackbook_gsap_app\mackbook_gsap_app\public\models\iphone-transformed.glb [511.8KB] (95%)
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-iphone-13-pro-2021-a35156d91cf44e70a2fdfeade54ae0b2
Title: (FREE) iPhone 13 Pro 2021
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Iphone13Pro2021(props) {
  const { nodes, materials } = useGLTF('/models/iphone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[-0.057, 0.789, -0.14]} scale={0.024} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial002} position={[-0.057, 0.789, -0.14]} scale={0.024} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial003} position={[-0.057, 0.789, -0.14]} scale={0.024} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material} position={[-0.057, 0.789, -0.14]} scale={0.024} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Display} position={[-0.057, 0.789, -0.14]} scale={0.024} />
    </group>
  )
}

useGLTF.preload('/models/iphone-transformed.glb')
